### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by garysassano** [FidelusAleksander/githubcertified#65]
I genuinely appreciate the project. It would enhance my experience if correct answers were instantly highlighted in green or red. This is especially useful for those who might not complete all the questions in one sitting but still want feedback on their performance. Alternatively, it would be helpful to view the correct answer directly by clicking on the light bulb icon, rather than navigating to the documentation link and searching for it.

Another feature I'd appreciate is the ability to either save our progress using a cookie or consistently present the questions in the same sequence, allowing users to jump to a particular question number. For those who enjoy tackling questions randomly, an option to shuffle and take a test with questions in a mixed order would be great.

**Comment by FidelusAleksander** [comment]
Hi @garysassano 

Thanks for the great feedback and suggestions. These are really good points

- Instant feedback (highlighting answers red/green)
- Study the questions in the same sequence
- Save progress

Personally I see this as a great idea for another section (other than Practice Tests) dedicated to studying all contributed questions in order. Maybe this section could be called **"Library"** (or something similar - I will have to think on it a little)

**Why another section?**
The Practice Tests one should mimic the official GitHub Exam experiance, where You actually do get random questions, and You wouldn't want all of the answers to be highlighted red/green until You decide to finish the entire exam and get graded

**Comment by garysassano** [comment]
Well done. Yet, there are a few points to note: the arrows intended for question navigation aren't operational. Moreover, rather than the animation that hides alternative options, I'd like all answers to be visible with an option to toggle the solution. Perhaps you could incorporate the correct answer's letter into the light bulb icon you're using.

**Comment by FidelusAleksander** [comment]
The arrows intended for navigation in the Questions section are "not working" because it's like a practice test but only with 1 question -> with somewhat instant feedback

I agree this is not ideal, at some point I might create(or find) something more custom for that piece but for now the [project](https://github.com/bonartm/quizdown-js) I'm using doesnt support more customizations.

However ...
In [#75](https://github.com/FidelusAleksander/githubcertified/pull/75 ) i've added a previous/next page button on the topbar. This one jumps between questions.

I'm closing this for now and I created another [issue](https://github.com/FidelusAleksander/githubcertified/issues/76) to address the UX improvements as I agree with You that these arrows are confusing + seeing all answers should be an option.

Thanks for raising the issue and all the feedback @garysassano !
